export const sampleUsers = [
  {
    name: "Aarav Mehta",
    email: "aarav.mehta@campus.edu",
    role: "student",
    department: "Computer Science & Engineering",
    studentId: "2024BCSE042",
    phone: "+91 98765 43210",
  },
  {
    name: "Sneha Reddy",
    email: "sneha.reddy@campus.edu",
    role: "student",
    department: "Electronics & Communication",
    studentId: "2024BECE019",
    phone: "+91 98765 43211",
  },
  {
    name: "Rajesh Kumar",
    email: "rajesh.guard@campus.edu",
    role: "staff",
    department: "Campus Security & Facilities",
    phone: "+91 98765 43212",
  },
  {
    name: "Ramesh Yadav",
    email: "ramesh.driver@campus.edu",
    role: "staff",
    department: "Campus Transport Services",
    phone: "+91 98765 43213",
  },
  {
    name: "Prof. Priya Sharma",
    email: "admin@campus.edu",
    role: "admin",
    department: "Dean of Student Affairs",
    phone: "+91 98765 43214",
  },
];

export const sampleAnnouncements = [
  {
    title: "Mid-Term Examination Schedule Released for Spring 2026",
    content: "The mid-term examination timetable has been officially published on the student portal. All students are advised to check seating arrangements and report any exam clashes before Friday.",
    category: "Academic",
    priority: "high",
    authorName: "Office of the Controller of Examinations",
    targetAudience: "students",
    isPinned: true,
  },
  {
    title: "Annual Technical Hackathon — HackPulse 2026 Registrations Open",
    content: "Join over 500 developers and creators for 36 hours of continuous coding, mentoring, and ₹1,50,000 in cash prizes. Open to all engineering departments.",
    category: "Events",
    priority: "medium",
    authorName: "Android & Developers Club",
    targetAudience: "students",
    isPinned: true,
  },
  {
    title: "Campus Wi-Fi Maintenance Window this Saturday",
    content: "Central IT will perform scheduled core switch upgrades between 11:00 PM Saturday and 4:00 AM Sunday. Internet connectivity in Academic Blocks 1 and 2 will be temporarily intermittent.",
    category: "General",
    priority: "medium",
    authorName: "IT Infrastructure Support",
    targetAudience: "all",
    isPinned: false,
  },
  {
    title: "Hostel Water Tank Cleaning Notice",
    content: "Water supply to Hostel Block B and Block C will be suspended from 10:00 AM to 2:00 PM on Wednesday for bi-monthly overhead tank sanitization.",
    category: "Hostel",
    priority: "low",
    authorName: "Hostel Management Committee",
    targetAudience: "students",
    isPinned: false,
  },
];

export const sampleEvents = [
  {
    title: "Android & Modern Web Dev Bootcamp",
    description: "Hands-on workshop covering Kotlin Jetpack Compose, React, Next.js App Router, and full-stack REST API development. Certificate provided on completion.",
    category: "Technical",
    venue: "Seminar Hall LH-1, Academic Block 1",
    date: "2026-09-15",
    time: "10:00 AM - 4:00 PM",
    organizer: "Android Club",
    capacity: 120,
    registeredCount: 45,
    bannerUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=60",
    status: "upcoming",
  },
  {
    title: "Open Source AI & Machine Learning Symposium",
    description: "Keynotes from industry researchers on local LLM fine-tuning, computer vision on edge devices, and open-source contributions for students.",
    category: "Workshop",
    venue: "Auditorium 2, Main Block",
    date: "2026-09-22",
    time: "2:00 PM - 6:00 PM",
    organizer: "AI/ML Student Chapter",
    capacity: 200,
    registeredCount: 88,
    bannerUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=60",
    status: "upcoming",
  },
  {
    title: "Inter-College Robotics Obstacle Challenge",
    description: "Autonomous line-following and obstacle navigation robot racing competition. Teams of 2-4 members.",
    category: "Hackathon",
    venue: "Indoor Sports Complex",
    date: "2026-09-28",
    time: "9:00 AM - 5:00 PM",
    organizer: "Robotics Society",
    capacity: 60,
    registeredCount: 30,
    bannerUrl: "https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?w=800&auto=format&fit=crop&q=60",
    status: "upcoming",
  },
  {
    title: "Campus Cultural Night & Music Fest",
    description: "An evening of band performances, dance competitions, and food stalls organized by the Student Council.",
    category: "Cultural",
    venue: "Open Air Amphitheatre",
    date: "2026-10-05",
    time: "6:00 PM - 10:00 PM",
    organizer: "Cultural Club",
    capacity: 500,
    registeredCount: 310,
    bannerUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&auto=format&fit=crop&q=60",
    status: "upcoming",
  },
];

export const sampleProjects = [
  {
    title: "CampusPulse — Smart Campus Operations",
    description: "Unified web portal for automated issue reporting, real-time ticket tracking, event management, and campus operational analytics.",
    clubName: "Android Club",
    category: "Web",
    teamLead: "Aarav Mehta",
    status: "active",
    githubUrl: "https://github.com/campus/campuspulse",
    demoUrl: "https://campuspulse.vercel.app",
    tags: ["React", "Next.js", "TypeScript", "MongoDB", "Tailwind CSS"],
  },
  {
    title: "Smart Classroom Energy Auditor",
    description: "IoT sensor system measuring power consumption, occupancy, and ambient temperature in lecture halls to auto-control air conditioning and lighting.",
    clubName: "IoT & Embedded Systems Lab",
    category: "IoT",
    teamLead: "Sneha Reddy",
    status: "recruiting",
    githubUrl: "https://github.com/campus/smart-energy",
    demoUrl: "",
    tags: ["ESP32", "MQTT", "Node.js", "Sensors"],
  },
  {
    title: "Autonomous Campus Mail Delivery Bot",
    description: "Self-navigating ground rover for internal campus document and mail delivery using LIDAR and ROS2.",
    clubName: "Robotics Society",
    category: "Robotics",
    teamLead: "Vikram Singhania",
    status: "active",
    githubUrl: "https://github.com/campus/mailbot-ros",
    demoUrl: "",
    tags: ["ROS2", "Python", "Computer Vision", "LIDAR"],
  },
];

export const sampleIssues = [
  {
    ticketCode: "CP-2026-100201",
    title: "AC water leakage causing a safety hazard",
    description: "The AC unit in AB1-305 has been leaking water since morning and students are slipping near the doorway.",
    category: "Air Conditioning (HVAC)",
    building: "Academic Block 1",
    room: "AB1-305",
    severity: "HIGH",
    status: "OPEN",
    reporterName: "Aarav Mehta",
    reporterEmail: "aarav.mehta@campus.edu",
    reporterRole: "student",
    assignedTo: "Rajesh Kumar (HVAC Lead)",
    resolutionNotes: "Technician dispatched to check drain pipe.",
  },
  {
    ticketCode: "CP-2026-100202",
    title: "Center ceiling fan sparking on speed 5",
    description: "Intermittent sparks observed from the ceiling fan regulator in AB2-204 during lectures.",
    category: "Electrical",
    building: "Academic Block 2",
    room: "AB2-204",
    severity: "CRITICAL",
    status: "IN_PROGRESS",
    reporterName: "Rajesh Kumar",
    reporterEmail: "rajesh.guard@campus.edu",
    reporterRole: "staff",
    assignedTo: "Electrical Maintenance",
    resolutionNotes: "Circuit breaker isolated. Replacing faulty speed regulator.",
  },
  {
    ticketCode: "CP-2026-100204",
    title: "Low water pressure in 3rd floor washroom",
    description: "Taps in Hostel Block B 3rd floor washrooms have near-zero water flow.",
    category: "Plumbing",
    building: "Hostel Block B",
    room: "3rd Floor Washrooms",
    severity: "HIGH",
    status: "RESOLVED",
    reporterName: "Ramesh Yadav",
    reporterEmail: "ramesh.driver@campus.edu",
    reporterRole: "staff",
    assignedTo: "Plumbing Department",
    resolutionNotes: "Replaced booster pump valve and cleared pipe blockage. Water flow restored.",
  },
];
